# lane_control/lane_controller_node

v_bar: 0.19
k_d: -6.0
k_theta: -5.0
k_Id: -0.3
k_Iphi: 0.0

# Fine-tuned angle thresholds
theta_thres_max: 0.75  # previously 0.523
theta_thres_min: -0.5

d_thres: 0.2615
d_offset: 0.0

omega_ff: 0.0

integral_bounds:
  d:
    top: 0.3
    bot: -0.3
  phi:
    top: 1.2
    bot: -1.2

# Extra (not directly used in controller yet but useful for filters)
d_resolution: 0.011
phi_resolution: 0.051

stop_line_slowdown:
  start: 0.6
  end: 0.15

verbose: 0
